version: '3.8'

services:
  webapp:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_USER_IDS=${ADMIN_USER_IDS}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
